# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    immediate_render = true
#    no_fade_in = false
#    grace = 0
#    disable_loading_bar = false
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, .65)
    font_size = 22
    font_family = SF Pro Display Bold
    position = 0, 70
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    #text = $TIME
    color = rgba(255, 255, 255, .65)
    font_size = 90
    font_family = SF Pro Display Bold
    position = 0, 0
    halign = center
    valign = center
}

# CURRENT QUOTES
label {
    monitor =
    text = cmd[update:60000] echo "$(~/.config/hypr/Scripts/get_quote.sh)" 
    color = rgba(0, 0, 0, 0.55)
    font_size = 17
    font_family = SF Pro Display Bold
    position = 0, 150
    halign = center
    valign = center
}
## USER-PHOTO
#image {
#    monitor =
#    path = ~/.config/hypr/user.png
#    border_size = 0
#    border_color = rgba(255, 255, 255, 0)
#    size = 105
#    rounding = 0
#    rotate = 0
#    reload_time = 0
#    reload_cmd = 
#    position = -105, 30
#    halign = center
#    valign = center
#}
#
## USER-NAME
#label {
#    monitor =
#    text = $USER
#    color = rgba(255, 255, 255, .65)
#    font_size = 22
#    font_family = SF Pro Display Bold
#    position = 0, 30
#    halign = center
#    valign = center
#}


# INPUT FIELD
input-field {
    monitor = 
    size = 50, 30
    rounding = 0
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    fade_on_empty = true
    #hide_on_empty = true
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}


## CURRENT SONG
#label {
#    monitor =
#    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)" 
#    color = rgba(255, 255, 255, 0.55)
#    font_size = 17
#    font_family = JetBrains Mono Nerd, SF Pro Display Bold
#    position = 0, 30
#    halign = center
#    valign = bottom
#}
